//
// Created by Hang XU on 21/10/2025.
//

#ifndef ECATV2_AX58100_H750_UNIVERSAL_SETTINGS_H
#define ECATV2_AX58100_H750_UNIVERSAL_SETTINGS_H

#define SW_REV "004"

/** DSHOT CONFS BEGIN **/
#define DSHOT1_TIMER_CLOCK 240000000
#define DSHOT1_TIM (&htim3)
#define DSHOT1_MOTOR_1_TIM_CHANNEL TIM_CHANNEL_1
#define DSHOT1_MOTOR_2_TIM_CHANNEL TIM_CHANNEL_2
#define DSHOT1_MOTOR_3_TIM_CHANNEL TIM_CHANNEL_3
#define DSHOT1_MOTOR_4_TIM_CHANNEL TIM_CHANNEL_4
#define DSHOT2_TIMER_CLOCK 240000000
#define DSHOT2_TIM (&htim2)
#define DSHOT2_MOTOR_1_TIM_CHANNEL TIM_CHANNEL_1
#define DSHOT2_MOTOR_2_TIM_CHANNEL TIM_CHANNEL_2
#define DSHOT2_MOTOR_3_TIM_CHANNEL TIM_CHANNEL_3
#define DSHOT2_MOTOR_4_TIM_CHANNEL TIM_CHANNEL_4
#define DSHOT600_HZ 12000000
#define MOTOR_BIT_0 7
#define MOTOR_BIT_1	14
#define MOTOR_BITLENGTH 20
#define DSHOT_FRAME_SIZE 16
// resolution + frame reset (2us)
#define DSHOT_DMA_BUFFER_SIZE 18
#define DSHOT_MIN_THROTTLE 48
#define DSHOT_MAX_THROTTLE 2047
#define DSHOT_RANGE (DSHOT_MAX_THROTTLE - DSHOT_MIN_THROTTLE)
/** DSHOT CONFS END **/

/** SOES CONFS BEGIN */
#define SLAVE_INITIALIZING 1
#define SLAVE_READY 2
#define SLAVE_CONFIRM_READY 3

#define MASTER_UNKNOWN 0
#define MASTER_REQUEST_REBOOT 1
#define MASTER_SENDING_ARGUMENTS 2
#define MASTER_READY 3
/** SOES CONFS END */

/** LED CONFS BEGIN */
#define LED_CONTROL_TIMER (&htim17)
#define LED_PSC 23999
#define LED_25MS_ARR 249
#define LED_250MS_ARR 2499
/** LED CONFS END */

#endif //ECATV2_AX58100_H750_UNIVERSAL_SETTINGS_H
